/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vnxspivndnccsduvhcuj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZueHNwaXZuZG5jY3NkdXZoY3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzgxMjUsImV4cCI6MjA3MzAxNDEyNX0.-oWcIq1bQoDtBNZ9eIFmTHSl0cyfxFPtrU2-9SGE_yA"